"""GENERATED FILE — do not edit by hand.

Kind: content vocabulary
Draft hash: 67941a023a4b
Generated at: 2026-05-19T00:50:01+00:00

Source: /admin/vocab curator (see docs/plans/categories-keywords-redesign.md).
Regenerate via POST /api/admin/vocab/compile or `photosearch compile-vocab`.
"""

CONTENT_VOCABULARY: list[str] = [
    'active play',
    'adult',
    'adult male',
    'adult woman',
    'animal',
    'architecture',
    'artificial lighting',
    'autumn',
    'baby',
    'backboard',
    'backdrop',
    'backpack',
    'backyard',
    'balcony',
    'ball',
    'bamboo forest',
    'bar',
    'baseball',
    'baseball bat',
    'baseball cap',
    'baseball game',
    'baseball glove',
    'baseball uniform',
    'basketball',
    'basketball court',
    'basketball hoop',
    'bat',
    'beach',
    'bed',
    'bench',
    'bird',
    'black jacket',
    'black pant',
    'black shirt',
    'black short',
    'black t shirt',
    'blanket',
    'bleacher',
    'blonde hair',
    'bloom',
    'blue jacket',
    'blue jean',
    'blue jersey',
    'blue pant',
    'blue shirt',
    'blue short',
    'blue sky',
    'blue t shirt',
    'blue uniform',
    'blue yellow jersey',
    'blue yellow uniform',
    'boat',
    'book',
    'bottle',
    'bouquet',
    'bowl',
    'box',
    'boy',
    'branch',
    'bride',
    'bridge',
    'building',
    'bush',
    'cake',
    'camera',
    'cap',
    'car',
    'car interior',
    'car seat',
    'car window',
    'carpet floor',
    'cartoon character',
    'casual sport attire',
    'casual sportswear',
    'celebration',
    'chain link fence',
    'chair',
    'child',
    'christmas tree',
    'city',
    'cityscape',
    'clear blue sky',
    'clear day',
    'clear sky',
    'cleat',
    'cliff',
    'cloud',
    'cloudy day',
    'cloudy sky',
    'cluster',
    'coach',
    'coastal cityscape',
    'collage',
    'community park',
    'conversation',
    'cool cloudy day',
    'coral',
    'coral reef',
    'costume',
    'couch',
    'countertop',
    'court',
    'crib',
    'crowd',
    'cup',
    'dark jacket',
    'dark pant',
    'dark shirt',
    'decoration',
    'deer',
    'desk',
    'different team',
    'dining area',
    'dining table',
    'dirt path',
    'distinctive brand',
    'distinctive landmark',
    'dog',
    'door',
    'dress',
    'drink',
    'early teen',
    'elevated vantage point',
    'family',
    'farm',
    'fence',
    'field',
    'fish',
    'floor',
    'floor indoor',
    'flower',
    'foliage',
    'food',
    'forest',
    'formal attire',
    'formal event',
    'framed picture',
    'furniture',
    'game',
    'game practice session',
    'garden',
    'gathering',
    'girl',
    'glass',
    'goal',
    'goal net',
    'goal post',
    'goalkeeper',
    'good weather condition',
    'grass',
    'grassy field',
    'green leaf',
    'green shirt',
    'greenery',
    'groom',
    'ground',
    'group',
    'group portrait',
    'guest',
    'gym',
    'gymnasium',
    'hat',
    'helmet',
    'high chair',
    'high vantage point',
    'highway',
    'hill',
    'hillside',
    'holiday season',
    'home',
    'home environment',
    'horizon',
    'house',
    'human activity',
    'indoor',
    'indoor soccer',
    'infant',
    'interior space',
    'jean',
    'jersey',
    'kitchen',
    'lake',
    'landscape',
    'large body',
    'large window',
    'leaf',
    'life jacket',
    'light color',
    'living room',
    'long hair',
    'lush greenery',
    'man',
    'marine life',
    'match',
    'meal',
    'meat',
    'monkey',
    'mountain',
    'mountainous area',
    'mountainous landscape',
    'natural beauty',
    'natural landscape',
    'natural light',
    'net',
    'ocean',
    'old man',
    'old woman',
    'onesie',
    'open field',
    'open grassy area',
    'open space',
    'organize team',
    'outdoor',
    'pacifier',
    'pajama',
    'panoramic landscape',
    'panoramic view',
    'paper',
    'parent',
    'park',
    'park recreational area',
    'park sport field',
    'partly cloudy sky',
    'path',
    'pathway',
    'people',
    'person',
    'person hand',
    'phone',
    'pink flower',
    'pink shirt',
    'plaid shirt',
    'plant',
    'plate',
    'play',
    'play area',
    'player',
    'playground',
    'pleasant day',
    'polished wooden floor',
    'potted plant',
    'practice session',
    'public space',
    'pumpkin',
    'purple flower',
    'purple jacket',
    'railing',
    'recreational area',
    'red jersey',
    'red shirt',
    'referee',
    'residential area',
    'restaurant',
    'river',
    'road',
    'rock',
    'rocky shoreline',
    'room',
    'rural area',
    'sand',
    'sandy beach',
    'santa hat',
    'scenic view',
    'school field',
    'school sport field',
    'scoreboard',
    'screen',
    'sea',
    'shadow',
    'shelf',
    'shin guard',
    'shirt',
    'shore',
    'shoreline',
    'shrub',
    'sideline',
    'sidewalk',
    'sign',
    'sky',
    'slight smile',
    'small object',
    'smartphone',
    'snow',
    'soccer',
    'soccer ball',
    'soccer game',
    'soccer goal',
    'soccer indoor',
    'soccer jersey',
    'soccer player',
    'social gathering',
    'sock',
    'spectator',
    'spoon',
    'sport',
    'sport attire',
    'sport ball',
    'sport equipment',
    'sport field',
    'sport uniform',
    'spring',
    'stage',
    'stone wall',
    'stream',
    'street',
    'striped shirt',
    'suit',
    'summer',
    'sun',
    'sunglass',
    'sunny day',
    'sunset',
    'supervisor',
    'swing',
    't shirt',
    'table',
    'tank',
    'team',
    'teenager',
    'television',
    'tent',
    'text',
    'tie',
    'toddler',
    'toy',
    'toy car',
    'train',
    'tree',
    'tree branch',
    'underwater environment',
    'uniform',
    'urban environment',
    'valley',
    'vegetation',
    'vehicle',
    'vine',
    'vineyard',
    'volleyball',
    'wall',
    'water',
    'water edge',
    'waterfall',
    'wave',
    'wedding',
    'white dress',
    'white flower',
    'white onesie',
    'white shirt',
    'white wall',
    'window',
    'windshield',
    'wine glass',
    'winter',
    'woman',
    'wooden fence',
    'wooden floor',
    'yard',
    'yellow jersey',
    'yellow shirt',
    'youth soccer game',
]
